### ISSUE TITLE
i tried to use this module, but it did not seem to work

### ISSUE THREAD

**Issue by sunnysideup** [ntd/silverstripe-autotoc#10]
Hi, 

I installed this module, it worked great, except that IDs not inserted into HTML content => links do not work in TOC.  What did I do wrong?

Also, why not extend HTMLText and add the `Tocification` in there as a method, just like `Nice` or `Summary`.  This will just add the anchors.

Thank you

Nicolaas
PS found your module here: http://ssmods.com/

**Comment by ntd** [comment]
Hi Nicolaas,

I just tested autotoc *1.2.0* against silverstripe *3.5.3* and it works as expected. Can you provide more info, e.g. silverstripe and autotoc versions, original HTML and augmented HTML, so I can try to replicate the problem here?

> Also, why not extend HTMLText and add the Tocification in there as a method, just like Nice or Summary. This will just add the anchors.

Currently the autotoc feature is really bound to the controller, based on the assumption "one page - one table of contents". I don't think it makes much sense to bound it to every HTMLText instance.

**Comment by ntd** [comment]
I updated the module for SilverStripe 4. I also added a couple of  [new template tags](https://github.com/ntd/silverstripe-autotoc/blob/master/docs/en/usage.md#usage) to address this issue.

Now you can use `$OriginalContentField` to explicitly access the original content field and `$ContentField` to access the augmented one. `$Content` by default should still return the augmented field (i.e. by default `$Content == $ContentField`) but there could be cases when this assumption is not true, e.g. if you define a `getContent()` method. In those cases, just use `$ContentField`.

@sunnysideup if you still have problems, feel free to reopen.

**Comment by sunnysideup** [comment]
thank you. Will do.
